### ISSUE TITLE
Walkthrough/Tour

### ISSUE THREAD

**Issue by felixgabler** [proteinevolution/Toolkit#1113]
Requirements:
- only for the first visit

Possible plugins:
- https://github.com/pulsardev/vue-tour
- https://github.com/sschandi/vue-page-guide

**Comment by felixgabler** [comment]
@vikramalva can you check out the branch and give us some more input about how you imagine the tour to look like? We will definitely need a better idea about which steps to show. UI also has to be improved.

**Comment by vikramalva** [comment]
@felixgabler I think it would best to meet in person and discuss this in detail.

**Comment by joeldomke** [comment]
Steps for the tour:

1. Toolbar
2. Search box ('Enter a job ID or a tool name')
3. HHpred
4. Input text box
5. Paste Example
6. Select structural/domain databases
7. Select proteomes
8. Customize parameters
9. Custom Job ID
10. Submit
11. Point to the job pane.
