### ISSUE TITLE
maxmind stuff is most likely outdated

### ISSUE THREAD

**Issue by zy4** [proteinevolution/Toolkit#1209]
I think the database GeoCityLite2 which the backend uses does not even exist anymore.

**Comment by felixgabler** [comment]
The database exists but they changed the way to get it. I remember that i adapted to the new way a year ago or so.

**Comment by zy4** [comment]
But is the database regularily updated? I think it is outdated.

**Comment by vikramalva** [comment]
It is regularly updated. It was last updated on Apr 19.
