### ISSUE TITLE
Refactor TEL

### ISSUE THREAD

**Issue by zy4** [proteinevolution/Toolkit#173]
There seems to be a lot which is going on but much is overhead and many things can also be deleted because they are unused.

The overall structure is more or less confusing and could be refactored by following a more conceptual and functional approach of how to wire dependencies and parameters together and of how to inject them into the right places.

**Comment by felixgabler** [comment]
We moved away from using the files under Tel/env in the toolkit itself. Only environment.sh still exists in order to be sourced by each node.
The most important variables are now included in the config.
This reduces complexity by a whole lot but still needs some more improving.

**Comment by zy4** [comment]
closing in favor of #705 where most of the part is to be done
