### ISSUE TITLE
development docker environment

### ISSUE THREAD

**Issue by zy4** [proteinevolution/Toolkit#196]
I think this is better than having a headless system

Closes #118

**Comment by felixgabler** [comment]
There is a problem with the akka configuration and I don't really have a clue about how to fix it.
It is related to this:
https://doc.akka.io/docs/akka/2.5/remoting.html#remote-configuration-nat

**Comment by zy4** [comment]
Can you elaborate more on what happens?

**Comment by felixgabler** [comment]
The toolkit immediately shuts down after reaching the "reload your browser" message.
There is some information about it when searching for "akka shuts down in docker", but none of the solutions seem to work for us.

**Comment by zy4** [comment]
do you have an application.conf?

**Comment by felixgabler** [comment]
The toolkit can now run in a docker container. However, neither tools nor databases exist yet. Will close this issue until #247 is done.
