### ISSUE TITLE
Migrate validation.ts to scalajs

### ISSUE THREAD

**Issue by zy4** [proteinevolution/Toolkit#317]
The validation in typescript is very verbose and is not a mithril component. It is therefore relatively easy to migrate it to scalajs where we can have it more succinct.
We can also extend the validation to the parameters and do so by using the pattern provided by 
cats.data.Validated (no more visitor pattern)

**Comment by felixgabler** [comment]
It will have to be done as a module in the new frontend. Closing this ticket in favour of the rewrite.

**Comment by zy4** [comment]
This will be part of the remaining scalajs code and not part of the vue.js code so reopen it to complete it.

**Comment by felixgabler** [comment]
This is part of the new frontend since it can be handled much easier and more dynamic there.
