### ISSUE TITLE
use camel case for json keys

### ISSUE THREAD

**Issue by zy4** [proteinevolution/Toolkit#359]
```scala
 implicit val jobFormWrites: Writes[JobForm] = (
    (JsPath \ "jobID").write[String] and
    (JsPath \ "state").write[JobState] and
    (JsPath \ "dateCreated").write[String] and
    (JsPath \ "toolitem").write[ToolForm] and
    (JsPath \ "views").write[Seq[String]] and
    (JsPath \ "paramValues").write[Map[String, String]](play.api.libs.json.Writes.mapWrites[String])
  )(unlift(JobForm.unapply))
```

Here we have camelCase keys for json fields which is non-conventional. If they were snake_case, we could use semi-automatic case class derivations, provided by play-json.

**Comment by felixgabler** [comment]
https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format

**Comment by felixgabler** [comment]
As far as I can tell, most people recommend using camelCase (Google, Airbnb, and Douglas Crockford, one of the main drivers behind json).
That's why we should also stay with it.
I'm closing this ticket now.

**Comment by zy4** [comment]
The problem is that most of our JSON is generated by third parties. Namely in `snake_case`.
For consistency it would be better to have uniformity, or not?

**Comment by anjestephens** [comment]
To me JSON and cc were going hand in hand, as javascript uses cc for property names and functions and anything in JSON is basically just an javascript object.
I prefer cc, as it uses less characters, but if there is a reason behind it, I would not mind switching to sc...
If a lot of the generated JSON files are using sc, we could actually differenciate between our code and 3rd party code by just looking at the identifiers, which is not a bad thing per se.

**Comment by felixgabler** [comment]
I don't particularly like the idea of mixing cc and sc.. In my opinion the API should stick to one case for every endpoint. What we could also do is using sc for transmission and applying a sc->cc conversion in the frontend before using the values. But I doubt that it's a good idea. What bothers me is just using snake case for all the API data and camel case for all local data. Would like to keep it uniform.

**Comment by zy4** [comment]
I also have sympathies for camelCase now. I also found out that the keys in mongo should be camelCased. Too bad, we just did the opposite. 
Who is in favor of enforcing camelCase and try to handle third party json as edge cases?

I also think that many of the result json files are under our control so that we could simply modify the scripts.

**Comment by felixgabler** [comment]
I will change all the keys back to camelCase asap
