### ISSUE TITLE
Status update mail not displayed correctly 

### ISSUE THREAD

**Issue by davidmrau** [proteinevolution/Toolkit#440]
The status update mail is not displayed correctly in my Mac Mail program, however if I open the mail on mailhost.tuebingen.mpg.de the mail is complete and displayed correctly. I guess the link is for some reason blocked from being shown.

![screen shot 2018-06-07 at 10 01 46](https://user-images.githubusercontent.com/20661461/41086407-45fb2c22-6a3a-11e8-9454-43fb0d405345.png)

**Comment by felixgabler** [comment]
@vikramalva, we could get a mail to be sent to your test MacBook and fix this minor issue today.

In general I think we could also try to create a better, unique mail template for our services.
https://mjml.io is a great resource for such things.
