### ISSUE TITLE
replace play-json with circe

### ISSUE THREAD

**Issue by zy4** [proteinevolution/Toolkit#606]

**Comment by felixgabler** [comment]
Please also write a test after the fix to prevent future reintroduction of this bug.

**Comment by felixgabler** [comment]
Could you make a list of where play-json is still used?

**Comment by zy4** [comment]
There is not much left. You can search for the string `play.api.libs.json` .
If #708 is done, there will be only some remnants in code I want to touch anyway later: the whole backend module which is a mess atm.
