### ISSUE TITLE
When a submitted job is deleted by a user it is now not removed from the SGE

### ISSUE THREAD

**Issue by vikramalva** [proteinevolution/Toolkit#620]
Even after a user kills a queued/running job within the Toolkit, it is now not killed by the SGE.

**Comment by felixgabler** [comment]
Please also write a test after the fix to prevent future reintroduction of this bug.

**Comment by zy4** [comment]
This is a very old bug (August 23, 2017), normally it is harmless because at some point the sge will terminate it. But I will restore the functionality for what it's worth.

**Comment by zy4** [comment]
going to defer the test part of it a little because it requires a bit of preparation so probably next week.
