### ISSUE TITLE
Help Button for HHpred Manual

### ISSUE THREAD

**Issue by zy4** [proteinevolution/Toolkit#632]
has no modal. Should be removed or a modal should be implemented.

**Comment by vikramalva** [comment]
Yes, that's the sole purpose. These jobs, however, frequently need several minutes to complete and that's why it is necessary to have the intermediate page.

**Comment by zy4** [comment]
Should all be handeled async in the background. In my opinion HTMP is not a tool and should be gone from the frontend.

**Comment by vikramalva** [comment]
Having this intermediate step allows users to do other things in parallel while waiting for the HTMP job to completely. If we would also handle it like forwarding, users would be bound to the parent page.

**Comment by zy4** [comment]
No, I was talking about dispatching a modeller job right away

**Comment by vikramalva** [comment]
That's not a good idea, as users should be provided with the option to refactor the alignment created by HTMP, before it is submitted to MODELLER.

**Comment by vikramalva** [comment]
Users can remove one or more template sequences from the created alignment and this does not require any refactoring of the code. This has been working very well all the time.

**Comment by zy4** [comment]
Okay, but to close this issue. If we stick to HTMP as a submission tool, we should decide whether we do away with the help icon.

**Comment by vikramalva** [comment]
Let's do away with it.
