### ISSUE TITLE
MODELLER error with forwarded template 

### ISSUE THREAD

**Issue by zy4** [proteinevolution/Toolkit#637]
8808874 has failed. It had 5904294 as parent job which selected all hits from 7169822

**Comment by vikramalva** [comment]
@zy4 I would not make new issues for MODELLER failures; these jobs fail multiple times a day. Some are linked to #629 and others to inconsistencies in the mmCIF files.

**Comment by vikramalva** [comment]
Also, it is not a good idea to post job ids here.
