### ISSUE TITLE
Show the 'Parent' button only if the parent job exists

### ISSUE THREAD

**Issue by vikramalva** [proteinevolution/Toolkit#651]
For MODELLER and HTMP.

**Comment by felixgabler** [comment]
THis should be closed after safarifix, right? #672

**Comment by vikramalva** [comment]
No. This is for a different issue. Presently, the 'Parent' button is shown irrespective of whether the parent job still exists or not. Before displaying the button, we should check for the possibility that the parent job was deleted.

**Comment by felixgabler** [comment]
closing in favor of #818.
It makes a lot more sense not to implement this twice on both branches.
