### ISSUE TITLE
Get CORS to work

### ISSUE THREAD

**Issue by felixgabler** [proteinevolution/Toolkit#679]
Currently axios fails because the backend does not allow cross origin request.

**Comment by zy4** [comment]
/cc @felixgabler 
https://groups.google.com/forum/#!topic/play-framework/IeIvF9p-mms

**Comment by felixgabler** [comment]
It is both configured in [/app/Filters.scala](https://github.com/proteinevolution/Toolkit/blob/8b728cf31151507c764622ef316b058cb64d242f/app/Filters.scala#L18) and in the application.conf (which needs serious refactoring). We should take a look at this again later on.
