### ISSUE TITLE
Vue: Display Loading State

### ISSUE THREAD

**Issue by felixgabler** [proteinevolution/Toolkit#680]
This could be something like a loading overlay [See this example](https://github.com/ankurk91/vue-loading-overlay), or we could implement a more comprehensive solution (inspired by [this](https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/src/router/routes.js#L107) e.g.).

**Comment by sesati** [comment]
Which loading state are you referring to, asynchronous component loading (which the second pattern is about) or axios backend calls (like [this](https://medium.com/@lachlanmiller_52885/a-pattern-to-handle-ajax-requests-in-vuex-2d69bc2f8984))
Or both of these?

**Comment by felixgabler** [comment]
Both. Every loading process which affects the user.

**Comment by felixgabler** [comment]
Looks good to me!

**Comment by felixgabler** [comment]
We will go over this again at a later point to refine the UX.
