### ISSUE TITLE
Vue: Auth

### ISSUE THREAD

**Issue by felixgabler** [proteinevolution/Toolkit#687]
We should start using JWTs to authenticate the users.
https://alligator.io/vuejs/vue-jwt-patterns/
The token should be stored in localStorage to allow the user to stay logged in.
It is important to also configure axios to always send the token with every request (perhaps as described in https://paweljw.github.io/2017/09/vue.js-front-end-app-part-3-authentication/).

This issue is connected to #610.

**Comment by felixgabler** [comment]
I would rather keep using sessions (http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/).

**Comment by felixgabler** [comment]
What there is still to do:
- the frontend has to be able to call the Auth routes through the AuthService.ts and get typed results back (they are defined in https://github.com/proteinevolution/Toolkit/blob/develop/modules/auth/src/main/scala/de/proteinevolution/auth/models/JSONTemplate.scala but can be changed if necessary)
- the login form has to be able to call the service methods and display results.
- registering and password forgot logic should be analogous and straightforward.
- when the user is logged in, his data should be stored in vuex => we need to access his modeller key (or the information that he has one at least)

**Comment by sesati** [comment]
Unfortunately emailing is not working with my local setup. 

When signing up a user, i get an internal server error (status code 500). It is caused by these two lines in the AuthController, in the signUpSubmit method:
```scala
val eMail = NewUserWelcomeMail(registeredUser, token.token, environment, env)
eMail.send
```
No error is thrown in the sbt console however, so it seems to be stuck at eMail.send, and then an internal server error is send.

Any ideas?

**Comment by felixgabler** [comment]
You will have to use a SMTP server like Google for example. I recommend something like the following:
https://support.teamgate.com/hc/en-us/articles/115002064229-How-to-set-up-Outgoing-SMTP-email-settings-while-using-2-step-verification-in-Gmail-
It is important to use an app password instead of your real Google password.

**Comment by felixgabler** [comment]
You can configure it in application-ext.conf by overriding the variables under play.mailer in application.conf.

**Comment by sesati** [comment]
Thanks, its working now. Note: To use the Google SMTP server, values for host, port and ssl have to be overridden as well.

**Comment by sesati** [comment]
There seems to be something wrong with the sessions, or i'm misunderstanding it.

If I send a request requiring a user (it contains the PLAY_SESSION id as a request cookie-header that was provided when logging in), the backend seems to be unable to resolve the correct user.

For instance if i call /auth/user/data, the request.user.userID and sessionID (in AuthController.getUserData) are different from the ones of the loggedInUser in the login function, so it seems like the wrong user is resolved and in particular userData is null.

**Comment by zy4** [comment]
/cc @sesati 
the PLAY_SESSION is a JWT token, you first need to decode it.
Within this token there is a key called "SID", you should take this one.

To decode JWT, you can use a library. Check the structure of the token here: https://jwt.io/

Don't forget to set the Authorization Header correctly.

**Comment by felixgabler** [comment]
As outlined in the article mentioned above, we shouldn't actually use JWT as they are not suitable for our use case.

**Comment by zy4** [comment]
Can you repeat the most critical points in your own words? PLAY itself is leaning strongly towards JWT. Otherwise, we would need to rewrite a lot of the backend. Also JWT is lightweight and has built-in CSRF protection. What @sesati should know is that he cannot use the current mechanism without JWT.

**Comment by felixgabler** [comment]
Currently the session is resolved through the PLAY_SESSION cookie, am I right? Why shouldn't it work now?

**Comment by zy4** [comment]
No, try to paste the Cookie into https://jwt.io/
You will find out that we were using JWT all the time :P

**Comment by felixgabler** [comment]
Ok, I didn't realize. One thing I don't like about jwt is that one cannot individually invalidate a token without using a blacklist.

**Comment by zy4** [comment]
When did we ever have to do this TBH?

**Comment by felixgabler** [comment]
Before I knew that we are supporting it already, I didn't see any advantages for us of changing. But with the same logic, I wouldn't switch back now.

**Comment by sesati** [comment]
Thanks for explaning. However, I still don't get why it doesn't work. The old toolkit also sends the JWT token as the PLAY_SESSION cookie in the cookie header:
![request_old](https://user-images.githubusercontent.com/25408093/54681567-00b48780-4b0d-11e9-84a8-ad4523940ca6.png)
The new frontend is also doing that, but I don't get any results.
![request_new](https://user-images.githubusercontent.com/25408093/54681600-132ec100-4b0d-11e9-9f38-7df06533a5b7.png)

**Comment by zy4** [comment]
You are most likely missing out on the `Authorization Header`
For example 
```
"Content-Type"  -> "application/json",
"Authorization" -> "Bearer SID-TOKEN (FROM THE JWT TOKEN)",
"Cookie"        -> PLAY_SESSION= ...
```

**Comment by felixgabler** [comment]
We also need a link to resend verification link

**Comment by sesati** [comment]
ToDos:

- Fix E-Mail verification links for production and development (introduce or use variables for hostname/port in application-ext.conf)
- Implement websocket logout command in frontend (see VerificationController, LogOut is forced after verification of password change)

**Comment by felixgabler** [comment]
I will create separate tickets for the remaining issues.
