### ISSUE TITLE
Add userID to user model

### ISSUE THREAD

**Issue by felixgabler** [proteinevolution/Toolkit#708]
We would like to get rid of BSONObjectIDs throughout our code.

**Comment by zy4** [comment]
Also the user model should be migrated to circe (which is one of the last places where play-json is in use)

**Comment by anjestephens** [comment]
As MongoDB will use it's own ID internally at any rate, it would be more practical to have a way of using the ID as a string instead of using two IDs. I guess I could do that by simply converting the ID in the objects readers / writers.

**Comment by zy4** [comment]
Please forget about the BSONObjectID completely. This is a completely internal detail which should be hidden from everyone.
And be aware that if you introduce a new field to the user model, that you would need to do a migration via mongobee.

**Comment by felixgabler** [comment]
The BSONObjectIDs are now fully gone from the code.
I wrote migrations for all the necessary database actions, so it should not be a problem to deploy these changes to production. However, at the moment any old instances using tkplay_dev will probably fail because the changes are already deployed there.
