### ISSUE TITLE
Report Migration Failures to the frontend

### ISSUE THREAD

**Issue by felixgabler** [proteinevolution/Toolkit#710]

**Comment by felixgabler** [comment]
I'm not sure if this is relevant now when we are working on decoupling front- and backend atm.
How would we solve it with an external backend?

**Comment by zy4** [comment]
It is hard to explain if you haven't seen it, but it would be similar to: https://github.com/flyway/flyway-play

**Comment by felixgabler** [comment]
Although it is kind of neat to have, in my opinion this is a bit over the top for the project. Considering how many migrations we have and how we deploy it, this seems hardly relevant. @zy4 are you ok with closing this issue?
