### ISSUE TITLE
HHpred is broken

### ISSUE THREAD

**Issue by vikramalva** [proteinevolution/Toolkit#727]
'Results' and 'Probability Plot' pages are broken following https://github.com/proteinevolution/Toolkit/commit/06f9db9cbe18335b3eef9524895d39c644b12e6a.

**Comment by zy4** [comment]
Thanks, good to know.

**Comment by vikramalva** [comment]
Some of those values in the HHpred output file are not always present.

**Comment by zy4** [comment]
We need to be able to tell which ones.

**Comment by vikramalva** [comment]
We did that previously with GetOrElse.

**Comment by zy4** [comment]
`getOrElse("")` is okay but `getOrElse(-1)` looks bad.
