### ISSUE TITLE
File upload is broken!

### ISSUE THREAD

**Issue by vikramalva** [proteinevolution/Toolkit#762]

**Comment by zy4** [comment]
In which sense? I tested it and it worked.

**Comment by zy4** [comment]
I restricted the content type to text files so that images etc can't be uploaded anymore.

**Comment by vikramalva** [comment]
I tried to upload a file containing protein sequences.

1. I am shown that the upload was successful. 

![upload1](https://user-images.githubusercontent.com/20257466/48905143-0650d800-ee61-11e8-8fec-78871993a4a2.png)

2. But when I submit the job, it fails.
![upload2](https://user-images.githubusercontent.com/20257466/48905187-26809700-ee61-11e8-9128-4e1b54890c52.png)

3. Actually, looks like the file was not uploaded at all.
![upload3](https://user-images.githubusercontent.com/20257466/48905211-339d8600-ee61-11e8-8893-990edeaf4e2d.png)

**Comment by zy4** [comment]
For me it still works. Please:

1. sbt clean and clear browser cache
2. send me your input file via email

**Comment by vikramalva** [comment]
I did those things before I created the issue. I sent you the file.

**Comment by zy4** [comment]
That is because of the ending. At the moment, only .txt files are accepted since we guess the ContentType from the file ending.

**Comment by vikramalva** [comment]
That's an issue. Typically, people use all kinds of filenames with or without extensions, e.g., in, in.fas, in.fasta, in.msa, and in.clu.
