### ISSUE TITLE
Vue: Store MODELLER key in profile when valid

### ISSUE THREAD

**Issue by felixgabler** [proteinevolution/Toolkit#768]
After it has been validated, the modeller key should be stored in the user profile and be used in later submissions.

**Comment by sesati** [comment]
Should we keep the functionality as it is?

Currently, the modeller key isn't stored in the user profile but just a boolean value indicating whether the user has the correct key. If this value is set, then the "validate/modeller" route just returns true every time, without regarding the input. The key is also not used in any further submissions, the frontend just displays that the key is stored if the backend validates the input.

**Comment by vikramalva** [comment]
@sesati let us keep this functionality as it is and continue using a boolean value to indicate whether the user has the correct key.

**Comment by sesati** [comment]
Implemented similar to current frontend.
