### ISSUE TITLE
application-ext should go

### ISSUE THREAD

**Issue by zy4** [proteinevolution/Toolkit#787]
there is no need for this file since we can override all values via environmental variables

**Comment by felixgabler** [comment]
I think environmental variables are a bad idea in general as they are much less explicit and one can easily lose track of which ones are set to what. 
If you look for best practices (environmental variables vs config files), you also get most people arguing strongly against env.

**Comment by zy4** [comment]
I think it is easier in terms of deployment to have environmental variables
If we allow an application-ext file than (like what has happened on production) the configuration can mutate away from the development config. This is what happened to the docker issue which was ascribed to Java's ProcessBuilder. The issue, though, stems from a hard-coded value for the path of `environment.sh` which was set completely different on production.

**Comment by felixgabler** [comment]
No, we actually threw away the other environment.sh file. Now we only use the one inside the project folder.

**Comment by felixgabler** [comment]
That was not the issue. Configuration is much easier when everything is in one place. @vikramalva what do you think?

**Comment by zy4** [comment]
Have you ever tried it on olt? Currently the toolkit does not even run on olt.

**Comment by vikramalva** [comment]
The old enviroment.sh file is not really used anymore on production; I am going to get rid of it soon. I also don't like the idea of setting environment variables in general, as not sourcing them correctly would cause issues.

**Comment by zy4** [comment]
We already rely on environment variables and not sourcing them correctly is not an option or argument anymore. I think that an external file leads to bad habits which are not well testable in the first place. We don't want to have multiple extensions flying around for test / stage / development and prod.

**Comment by felixgabler** [comment]
We do not rely on environment variables that much anymore. They are only used to override values from the config. This way it is possible to see all of the config values just by looking at a few files in one place. That is really valuable in my opinion.

**Comment by zy4** [comment]
Another issue I have with the ext config is that commits such as https://github.com/proteinevolution/Toolkit/commit/fd7ed08eced9e2eb7f7efd68461fde1e33c1965b

are not possible anymore. This commit is misguiding. user and password have to be set and are NOT OPTIONAL. The config should always be self-documentary if possible. 

If I don't know what somebody, in this case @vikramalva , wrote in his ext config, I will get tempted to misconfigure my runtime.

**Comment by vikramalva** [comment]
@zy4 @felixgabler I am also leaning in favor of getting rid of application-ext. Setting variables in .bashrc also has the advantage that once they are set for the master node, variables are also available to the SGE nodes. Let's not rush with this. @felixgabler let's discuss this some more when I am back.

**Comment by felixgabler** [comment]
@note what is your take on this? Any suggestions about how to manage config variables between different machines?

**Comment by felixgabler** [comment]
It has proven quite comfortable and useful to have an application-ext.conf. I don't think this issue is necessary

**Comment by felixgabler** [comment]
This is what you do for testing:
https://www.pmatiello.me/2014/12/using-a-different-configuration-file-when-running-tests-in-a-play-project.html

**Comment by felixgabler** [comment]
I discussed this with @vikramalva and we like this way of configuring the application. This is why I will close this issue
