### ISSUE TITLE
unify UserSessions getUser methods

### ISSUE THREAD

**Issue by felixgabler** [proteinevolution/Toolkit#798]
I believe they should both first check cache, then database and then create one if necessary. Right now they behave rather different.

**Comment by zy4** [comment]
I would rather get rid of the getUser stuff. I would rather use Action Composition in the future without having a cache for this at all: https://www.playframework.com/documentation/2.6.x/ScalaActionsComposition#authentication

**Comment by felixgabler** [comment]
Eventually we would want to use JWT for it anyways, right? Everything would be done using the JWT token then

**Comment by zy4** [comment]
let's first get rid of the getUser method. Going to implement this with JWT.

**Comment by felixgabler** [comment]
I am actually leaning strongly against JWT atm.
http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/
