### ISSUE TITLE
Blast 2.8.1 is out!

### ISSUE THREAD

**Issue by zy4** [proteinevolution/Toolkit#802]
https://ncbiinsights.ncbi.nlm.nih.gov/2019/01/04/blast-2-8-1-with-new-databases-and-better-performance/

**Comment by felixgabler** [comment]
We would also need new BLASTDBv5 databases. Maybe we can also create one for docker as well.

**Comment by vikramalva** [comment]
There is no documentation on building BLASTDBv5 databases locally yet.
