### ISSUE TITLE
MODELLER broken

### ISSUE THREAD

**Issue by vikramalva** [proteinevolution/Toolkit#809]
-Works normally when the input example is pasted.
-Breaks when a MODELLER job is initiated from within HHpred output
-Works normally on production

![screenshot_2019-02-05 modeller bioinformatics toolkit](https://user-images.githubusercontent.com/20257466/52272812-37ad5000-2948-11e9-8edf-d2e31e408086.png)

**Comment by zy4** [comment]
could be an issue with reformat. what does the js console say?

**Comment by zy4** [comment]
maybe git submodule update?
