### ISSUE TITLE
Vue: Lazy load Help Modals

### ISSUE THREAD

**Issue by sesati** [proteinevolution/Toolkit#817]
We have to find a way to lazy load the help modals that are currently statically included in the i18n translation file ([en.ts](https://github.com/proteinevolution/Toolkit/blob/vue/frontend/src/i18n/lang/en.ts)) and therefore being loaded immediately.

This could possibly be achieved using [vue-i18n-loader](https://github.com/kazupon/vue-i18n-loader) and packing the help modal contents into single-file components.

**Comment by felixgabler** [comment]
vue-i18n-loader does not work for this application. I wrote some custom functionality for this but at the moment I'm having problem with webpack dynamic imports. It is loading everything in the beginning and then lazily again when it is needed.

**Comment by felixgabler** [comment]
The problem seems to be that webpack automatically uses prefetch.Somehow the ways of disabling this behaviour do not work. It might be that this gets fixed in later versions of webpack. Right now, there is not much we can do.
