### ISSUE TITLE
Vue: try to find similarities between results

### ISSUE THREAD

**Issue by felixgabler** [proteinevolution/Toolkit#820]
Before we begin implementing the result views, we need to thoroughly think about how to do it as elegant as possible. Therefore we must try to find as much common ground between the different result views as possible.

**Comment by zy4** [comment]
I would define components. Each tab is a component. The more generic ones can be shared of course. But don't be too clever. A little code duplication might be good in order to build in custom features there which are not needed elsewhere!

**Comment by zy4** [comment]
Also an important design principle IMHO is: flat structures over nested ui components!
