### ISSUE TITLE
Vue: Implement correct validation parameters for tools

### ISSUE THREAD

**Issue by sesati** [proteinevolution/Toolkit#910]
Currently the validation parameters defined in the new frontend are not being passed correctly by the backend (see ToolConfig.scala, a stub is inserted here at the moment).
There needs to be a way of configuring the correct sequence formats/sequence types for every tool, so that the correct values can be passed upon calling the UI routes.

**Comment by sesati** [comment]
As an example, MODELLER only accepts PIR alignments, so this should be specified accordingly.

**Comment by felixgabler** [comment]
@vikramalva the configuration is optional. If sequence_restrictions.formats is not specified, it will automatically use Seq("FASTA", "CLUSTAL") per default. The default type is "PROTEIN". Is this ok?
Eventually, you would have to go over the tools and correct it for each tool.

**Comment by sesati** [comment]
While we are at it: We have to do the same for the input type ("sequence", "regex", "pdb" or "accessionID"). Currently "sequence" is passed statically for every tool. As an example, PatternSearch needs "regex".

**Comment by vikramalva** [comment]
@sesati @felixgabler I looked through input validation presently and found a few issues that need to be addressed:

- [ ] We presently don't distinguish between single sequence and multiple sequence inputs. Some tools like Quick2D and TPRpred require the input to be a single sequence in FASTA format, while others like HHblits, HHpred, and PSI-BLAST accept both single and multiple sequences. Also, some tools require that when the input comprises multiple sequences, they all be of the same length (multiple sequence alignment). 

- [ ] We should auto-convert CLUSTAL and STOCKHOLM format inputs to FASTA.

- [ ] We also need to limit the maximum number of characters allowed in an input as well as the maximum number of characters in individual sequences and the maximum number of sequences in multi FASTA inputs.

**Comment by sesati** [comment]
As for feature 1 and 3: These are actually already implemented in the new frontend (see [util/validation.ts](https://github.com/proteinevolution/Toolkit/blob/vue/frontend/src/util/validation.ts) and [SequenceValidationParams](https://github.com/proteinevolution/Toolkit/blob/vue/frontend/src/types/toolkit/tools.ts)). We just need to pass the correct parameters from the backend and configure them in tools.conf. We can also set default values for any of these parameters if appropriate. 

If only a single sequence is accepted, one can set maxNumSeq to 1 for this tool.

The auto-conversion to FASTA should be working now.

**Comment by sesati** [comment]
I added the possibility to configure the additional parameters in tools.conf.
@vikramalva Should we set the parameters according to the current validation code or do you want to go over the tools.conf yourself?

**Comment by vikramalva** [comment]
Thanks @sesati. I am going to go through the tools and set the correct parameters.
