### ISSUE TITLE
Vue: Set MSA generation iterations to 0 when input is MSA

### ISSUE THREAD

**Issue by vikramalva** [proteinevolution/Toolkit#919]
The input MSA can be in the following formats: FASTA, CLUSTAL, A3M, or STOCKHOLM.
This applies to the following tools: HHpred, HMMER, HHrepID, and HHomp.

When the user goes back to using a single sequence, the default iterations should be used.

For PCOILS and DeepCoil, the input mode could be chosen based on the user input.

**Comment by felixgabler** [comment]
What should happen for HHpred dual sequence mode?

**Comment by felixgabler** [comment]
I implemented the rest of the functionality. Please test!
