### ISSUE TITLE
dynamic user utc offsets

### ISSUE THREAD

**Issue by zy4** [proteinevolution/Toolkit#927]
At the moment, the UTC-offset is hard-coded.
We could implement the following logic:

1. Add a field time_zone to the user collection
2. When a user registers or gets stored, parse the time_zone from the ip (but also provide a way to change this later)
3. when datetimes are displayed in the ui, recalculate (server-side) the offset according to the time_zone field in the user collection
4. there could also be a timezone handler which checks if the time_zone has changed for a user and updates the entry in the db.

**Comment by felixgabler** [comment]
A simpler approach would be continuing to store everything as UTC and change it in the frontend using moment.js:
`moment.tz(moment.utc(datetime), moment.tz.guess());`
We would only have to change it at a few places (Job Detail View and JobManager)

**Comment by felixgabler** [comment]
We are only using human readable dates in the new frontend. This removes the necessity for such a feature.
