### ISSUE TITLE
Vue: Result files for search tools

### ISSUE THREAD

**Issue by sesati** [proteinevolution/Toolkit#939]
Currently, there are two issues with the result files of HHpred (and possibly other search tools):

- [x] The /results/alignment route doesn't work (See Query Template MSA Tab - we get a 404 not found error). @felixgabler It would be nice if you could investigate this.
- [x] The entire results file has to be loaded for the probability plot tab. We could improve this by creating a separate file in the results folder containing just the probabilities, which can then be loaded in the frontend. One would have to manipulate the runscripts for this. @vikramalva What do you think about this? We could also postpone this for later.

**Comment by vikramalva** [comment]
@sesati that's a good idea! We also need a view to display the distribution of E-values for tools like HHblits and PSI-BLAST. We could refactor the probability plot view to handle this too.

**Comment by sesati** [comment]
Fixed (See [here](https://github.com/proteinevolution/Toolkit/commit/0588ce45759042abdb78180b109830ec7665e4fd) and [here](https://github.com/proteinevolution/Toolkit/commit/7c3115532408040be2fa6aebc0ffc2edd47e12f4)).
