### ISSUE TITLE
Vue: Mobile menu

### ISSUE THREAD

**Issue by felixgabler** [proteinevolution/Toolkit#941]
Research different vue menu components (start here https://github.com/vuejs/awesome-vue#menu). Collect and document all findings in this issue (with links). Afterwards we can decide which menu we like best and implement it.

**Comment by conrizzo** [comment]
Reading through more menu examples in Vue. I tried all the examples in the link. https://romainsimon.github.io/vue-simple-search-dropdown/ Interesting feature to have option to be able to type text that searches a drop menu. Basic menu options here could be customized too https://michitaro.github.io/vue-menu/?Sample1
