### ISSUE TITLE
HHomp Help page shows variable names instead of content

### ISSUE THREAD

**Issue by anjestephens** [proteinevolution/Toolkit#959]
![Unbenannt](https://user-images.githubusercontent.com/20257444/64065731-9eaa9300-cc11-11e9-9203-d7a93b0066a0.PNG)

**Comment by sesati** [comment]
The problem is that HHomp is missing a help page, i.e. there is no file hhomp.ts under frontend/src/i18n/lang/extras/modals/toolHelp. One would either have to write a help page or disable the button if no content is found.

**Comment by vikramalva** [comment]
I am going to fix this soon. I don't recall if we had a help page for HHomp in the old front-end.

**Comment by sesati** [comment]
I don't think we had one - at least there is no twirl view in the backup branch.
