### ISSUE TITLE
ClustalAlignment and FastaAlignment tabs: 'Select All' + 'Forward  Selected' doesn't forward all sequences

### ISSUE THREAD

**Issue by vikramalva** [proteinevolution/Toolkit#979]
Only the first 50 sequences, which are shown by default, are forwarded. @sesati let's talk about this to find an elegant solution.

**Comment by sesati** [comment]
@vikramalva This should solve the issue. Please let me know if it works correctly.
@felixgabler and @vikramalva: What do you think of the design? The ForwardingModal is becoming quite big now, so we could split it and use a mixin to share common functionality.

**Comment by vikramalva** [comment]
@sesati works correctly now! Could you make a pull request? Splitting ForwardingModal would definitely make it easier to maintain.
